### ISSUE TITLE
Setting the symbol color with a Group selected hue-shifts all the symbols

### ISSUE THREAD

**Issue by HybridEidolon** [malulleybovo/SymbolArtEditorOnline#10]
Steps to reproduce:

1. Add a few symbols into a Group with a particular color
2. Select the Group
3. Set the color while the Group is selected

Expected: should set the color of all the symbols in the group to the selected color

Actual behavior: seems to hue-shift everything based on what you've selected?

Additionally, the color choice when selecting a group is shown as the default red color.

Selection color unchanged:

![image](https://user-images.githubusercontent.com/141511/85076663-2ef89b00-b186-11ea-8f5e-bdea287edc42.png)

Notice I've selected light blue here, but the actual color is much darker:

![image](https://user-images.githubusercontent.com/141511/85076684-39b33000-b186-11ea-9e04-59dc1ff9bb50.png)

**Comment by malulleybovo** [comment]
As weird as this sounds, that is like that by design. It is one the things I am not too fond of how it turned out. Unlike the color picked for the symbol (which sets the color of the symbol to the color on the black dot inside the picker), the color picker for the group controls hue (colorful bar on the right), saturation (x-axis of the square palette on the left), and brightness (y-axis of the square palette on the left); HSL, for short. The motivation for this was that groups wont normally have only one color. For example, imagine a group containing the eye of a character. The eye will contain multiple colors, so in cases like these an HSL filter works great. That said, I am not fond of using the current picker for HSL since it's confusing to say the least... I might rearrange this and perhaps include a few different filtering options when I find time.

**Comment by malulleybovo** [comment]
421a0379abb9916a20c4e0700b054c1fda2ba440

**Comment by malulleybovo** [comment]
New features are now available in the editor.
New Color Filters were now added to the editor. The legacy color picker seen in your screenshot has been removed.
Filters included:
- Color correction (hue, saturation and lightness): Changes the image tone of symbols within a group to any tone existent (similar to how contrast/saturation/brightness filters work).
- Color channels (red, green, blue channels): Adds/Subtracts a percentage of the respective color channel of symbols within a group.
- Set color: Sets the color of symbols within a group to any desired color. Comes with a checkbox that, if checked, forces all symbols in the group to match the color chosen. If unchecked, it changes the color but keeps the brightness to retain the shape of the image.
