### ISSUE TITLE
help : reducing size of the whole symbol

### ISSUE THREAD

**Issue by DarkForestNymph** [malulleybovo/SymbolArtEditorOnline#11]
i made a png drawing for pso2 and then i used a bunch of symbols to re-create the drawing. i wanted to use it for a clan symbol.. but now its waayyy to big. and i see when ya select the main folder that you can move it around the whole symbol art.. but is there anyway to reduce the size as a whole symbol ??
![pso2 symbol](https://user-images.githubusercontent.com/67160290/85152876-ced12a00-b255-11ea-9cd4-4c96eb0a0a92.jpg)

**Comment by malulleybovo** [comment]
Thanks for the interest in the editor. Before answering your question, let me clarify that the editor only has support for regular SAs (the big ones displayed in chat), not team symbols (the much smaller ones). I'm afraid the space to work with in the case of team symbol SAs is too small to be accurately presented using a canvas on the web (it really is small if you open the editor in game). So an intricate design like the one in your image (which looks great by the way) will probably not look great when downsized that much. Plus, team symbol SAs have a much lower limit on the number of symbols you can use (136 symbols greatly exceeds that). Now onto the answer:
The idea of resizing a group of symbols was considered during development, but was dropped due to a certain level of incompatibility with how each symbol is discretely positioned (without getting into math details, it is like every corner of every symbol can only be placed in specific spots, not just any spot like an SVG file). This proved to be a concern when resizing more than one symbol at once since the overall image would get distorted, which is undesirable. That is why there is no such feature in the editor. If I observe this is still of interest for many people regardless of the distortion, I might consider adding the functionality in when I find time.

**Comment by DarkForestNymph** [comment]
oh alright thank you for the awnser. so its kinda a feature request.. i guess the only way to have my drawing as a clan logo is to make it manually smaller.. .. well that sucks..
i dont know how many people will use your program or how many will ask for this feature. ( it will probably will be a longggg time until ya add it) but thank you anyway for responding - and thanks for liking my re-created drawing in ya program ^^

**Comment by malulleybovo** [comment]
@DarkForestNymph if you’re still interested, please check out v2.0.0 which adds in support for Alliance Flag (Team Flag) as well as multi-symbol resizing.

**Comment by DarkForestNymph** [comment]
> @DarkForestNymph if you’re still interested, please check out v2.0.0 which adds in support for Alliance Flag (Team Flag) as well as multi-symbol resizing.

alright. thank you 😄
