### ISSUE TITLE
Incorrect colors.

### ISSUE THREAD

**Issue by BobVonBob** [malulleybovo/SymbolArtEditorOnline#14]
I've been struggling with an issue where colors in this editor appear darker than ingame colors, and it seems to be a result of colors not saving correctly. See the following example.

These three circles were set to colors #000000, #ffffff, and #006600 respectively.

![Symbol Art](https://user-images.githubusercontent.com/34696418/87922472-aa799080-ca41-11ea-9bba-6e45ada64a8b.png)

However, the generated saml file, as well as the sar file, had these colors changed to #606060, #fcfcfc, and #5ba75b.
```xml
<?xml version="1.0" encoding="utf-8"?>
<overlay-img src="https://malulleybovo.github.io/SymbolArtEditorOnline/images/tile.png" pos-x="960" pos-y="480" scale="1" rot="0" alpha="0.5" green-screen="false"/>
<sa name="Symbol Art" visible="true" version="1" author="0" width="192" height="96" sound="3">
	<layer name="Symbol 0" visible="true" type="240" color="#fcfcfc" alpha="1" ltx="-32" lty="-32" lbx="-32" lby="32" rtx="32" rty="-32" rbx="32" rby="32"/>
	<layer name="Symbol 1" visible="true" type="240" color="#606060" alpha="1" ltx="-94" lty="-31" lbx="-94" lby="33" rtx="-30" rty="-31" rbx="-30" rby="33"/>
	<layer name="Symbol 2" visible="true" type="240" color="#5ba75b" alpha="1" ltx="29" lty="-32" lbx="29" lby="32" rtx="93" rty="-32" rbx="93" rby="32"/>
</sa>
```

![Annotation 2020-07-20 041930](https://user-images.githubusercontent.com/34696418/87922943-4b684b80-ca42-11ea-8481-479abffe423e.png)

Even stranger is when loading from the exported saml or sar files, colors appear to be what they were set as originally until the symbol is selected and the color picker opened and closed.

**Comment by malulleybovo** [comment]
Could you provide examples of expected in-game color versus the actual colors is the online editor? Does every color show wrong, or only a few?

I believe the game uses some color filter to display images in-game, so the colors from .sar files are not identical to the colors shown in-game. The online editor tries to replicate that color filter to display images in the editor by keeping the raw colors in the .saml/.sar files and interpolating them before displaying them in the editor/color picker. Thus why you see a divergence in the values. If you are observing differences in color between the game and this editor, it’s highly likely that it is due to inaccuracy in the color filter used in the editor.

**Comment by BobVonBob** [comment]
Here's that three circle image after manually editing colors in the saml file and exporting a sar from that.
![Annotation 2020-07-20 224815](https://user-images.githubusercontent.com/34696418/88011405-da29a680-cadc-11ea-9906-c030a358794e.png)

And here's a comparison of a symbol art made in the editor vs ingame appearance.
![UnsettledTom](https://user-images.githubusercontent.com/34696418/88011471-004f4680-cadd-11ea-9230-6dee75ea5858.png)
![unknown](https://user-images.githubusercontent.com/34696418/88011482-09401800-cadd-11ea-8498-45510be9f505.png)

It appears that dark colors are more heavily shifted by the editor filter than they are ingame, although that might just be me extrapolating too much from the dramatic effect it has on black.

**Comment by Griffinith** [comment]
I can chime in on this a bit. I've been thankful such a tool has been made and is as user friendly as it is.. however, the coloring correction has been a thorn in my side to the point that I currently don't even try to color things within this editor, I just use primary colors for different parts and color everything once I'm in game. Below are some examples of one of my arts which I used this.

![sample3_1](https://user-images.githubusercontent.com/71607015/93720706-b6282700-fb58-11ea-8afd-b5030259bc9c.png)
This was the SAR saved from this editor, unaltered and as an in game screenshot

![sample1](https://user-images.githubusercontent.com/71607015/93720500-672dc200-fb57-11ea-9897-392623473a65.png) 
After I recolored it in game.

![sample2](https://user-images.githubusercontent.com/71607015/93720527-a3612280-fb57-11ea-8b8c-00d26573c64a.png)
after importing into this editor with no changes made. It's much darker overall.

![sample3](https://user-images.githubusercontent.com/71607015/93720545-be339700-fb57-11ea-8933-332e0c096fb7.png)
This is the same image after I selected each layer, opened the color selector, and clicked ok without changing anything...

And finally:
![sample4](https://user-images.githubusercontent.com/71607015/93720561-d73c4800-fb57-11ea-8235-76f8ab542f5a.png)
This is the same symbol art after repeating that same process 5 times. I also learned clicking ok wasn't needed, you can just open the color picker and move to a different layer.

I'd love to be able to color with this editor instead of in game as I can be sure I get each symbol to match the others, and after looking at the examples, especially the difference from the recolored (second image) and the imported recolored (third image), I can see what the thought behind the color correction is. From what I can see, the lightening is a bit heavier than it needs to be, and it shouldn't affect the coloring of the "true" image, just the preview of that image.

**Comment by AvecPardon** [comment]
There's also something else related to color issues, namely that sometimes a symbol is selected and the color changes to a different shade/tint and won't be changed back, even if the hex code is copy/pasted into the colorpicker box.

**Comment by Markolise** [comment]
I have also been experiencing the color issues.
Had to go in and manually edit the SAML file to correct the colors. Made an Asuna Symbol Art I made look like she had a 5 o'clock shadow. Color of the face was set to this #fcf8e3, but kept being reset to #fbf6e3 or #fff3e3. Not sure why. Manually fixing the color setting in the SAML and re-importing/re-exporting to SAR fixed the issue.

**Comment by Jwguy** [comment]
Color picker doesn't change anything, for me, anymore. Everything is just white.

**Comment by malulleybovo** [comment]
Your troubles have been heard. The incoming release will correct the color accuracy, along with a brand new user interface with faster loading time, more fluid interaction and controls. Stay tuned.
