### ISSUE TITLE
Add imported layer to group?

### ISSUE THREAD

**Issue by thirteenf** [malulleybovo/SymbolArtEditorOnline#15]
Hi, thanks for making this available to the community. After importing a Screenart to begin editing, I can create a group, but I cannot seem to add the imported layers to it. 

I want to use this tool to group layers so that I can move them around in my design

**Comment by malulleybovo** [comment]
Hello, if I understood your question correctly, the way to insert a layer inside a group is to:
- if the group is empty, right click and select the option to add a layer inside.
- if the group has layers inside already, you can drag other layers with your cursor into the group.
Note that this not so intuitive behavior is due to the possibility to drag layers into empty groups was not implemented.
