### ISSUE TITLE
Legacy Download or Access

### ISSUE THREAD

**Issue by Axellogic** [malulleybovo/SymbolArtEditorOnline#19]
Is there a method to download or at least access the old version. I cannot understand how to edit entirely in 2d. This new version is incredibly tedious to navigate. 
It also does not allow for quick drawing at all with the symbols it took me 5 minutes to do 3 symbols which would have taken me 15 seconds on the old version. 
Is there a method to edit completely without the 3d view? The 3D side view makes the entire workflow impossible to follow and groups are extraordinarily unclear. Unless I am missing something I don't understand the direction you are taking the editor at all.

**Comment by malulleybovo** [comment]
Hello,

I apologize for the any frustration you may have gone through. Currently, there is no webpage hosting the legacy version of the project on this repository. (though you may find one in an outdated clone)

If you really wish to use the legacy version, you could clone the repository at an earlier commit and either host it locally or on GitHub. However, I'm more interested in knowing what caused your frustration in detail. Lets go one step at a time to understand the pain before proposing a solution.

1. Have you checked out the tutorial page? In it you can find a guide to the major mechanics of the editor to speed up editing time (https://github.com/malulleybovo/SymbolArtEditorOnline/wiki/Tutorial or via help button in the editor upper left menu).
2. Can you give examples of tasks you perform that are "tedious" to do in this version? For example: "I add symbols in bulk, but adding one at a time using the plus button is time consuming"
3. Could you elaborate on "quick drawing"? Or why it took you much longer to do 3 symbols?
4. Could you detail what you're finding hard to understand in the layer mode (3d view) and what were your expectations vs reality on this matter? For example: "I want to do X, but there is only a way to do Y" / "I want to find a certain symbol, but I cannot understand the UI in the 3d view"

Hints to minimize the use of layer mode (from the tutorial):
- press and hold left click button (or finger) to select the nearest symbol. Pressing and holding again cycles through the symbols where the mouse cursor is. Use this to change which symbol you're editing (example below)

https://user-images.githubusercontent.com/14852459/145661894-ad427482-67b6-4e46-846c-5cc93ca2bab8.mov

- layer editing (the sidebar in the legacy version) is now done via layer mode. Press and hold left click button above the layers to add a layer without using the plus button, then drag it into position. (example below)

https://user-images.githubusercontent.com/14852459/145662040-c5e56526-6f15-4453-b0b8-70e3354eb4d2.mov

- press space to switch between layer mode (3d) and symbol mode (2d).
- to quickly find the symbol you're editing in symbol mode (2d), press and hold it, then press space to bring it to view in layer mode (3d). (example below)

https://user-images.githubusercontent.com/14852459/145662193-290bbdf9-6f79-4226-a517-b2be6e9a18ee.mov

Now lets discuss.

**Comment by Axellogic** [comment]
Well pressing in holding by itself is a wholly tedious input that greatly lowers the speed at which you can create symbols.
As for speed often my method in symbol art creation is to draw some basic outlines to set up the shape. This I would typically do via copy and pasting the same shape or  line symbol multiple times until I have the shape set properly as id like.. In the legacy version You merely click the side bar, copy and paste into the group I have created.

 With this new method I have to toggle layer mode then select copy then click and hold and wait for a layer to be created then toggle back to 2d mode to place the symbol where I would like then repeat this process for every layer. It is not conducive to the workflow to have so many toggles and holds. Sure it looks nice I guess but its not efficient. It feels like its wasting my time and making it harder to focus on the drawing itself. 

Also the new display for groups makes it very difficult to see where they start and begin at a glance where it was fairly simple before. And viewing my groups on my old SAs I created in the old method reveal just how impossible it is to view the organized list as the groups view looks incredibly small. That and click dragging to move the list is much slower then simply mouse wheeling a sidebar.

Its less that I can't use it and more that the workflow makes me not want to. Understanding how to create the layers wasn't my problem its the extra steps it adds for no real benefit on my end. Also the 3d side view for the layers makes it difficult again to find a specific symbol in a specific spot like the in-game editor if there are many symbols layered on top. In the legacy version this was mitigated by just properly labeling the groups and symbols and clicking the symbol in the sidebar to find the exact symbol whereas with the side view symbols can easily get lost in the layers and are not obvious in the view. 

I can likely state other issues but I am a bit busy at the moment. I am likely going to work on a clone. The old version had some frustrations (such as with colors changing values from what were set if edited) but was wholly more intuitive and thus why I enjoyed using it.

**Comment by malulleybovo** [comment]
Thanks for sharing the feedback. Since the new interface is here to stay, I’d love to hear what is working and what isn’t, and improve the experience based on user input. Granted, when I’m free to work on this side project.
I’ve studied your complaints and sketched a few improvements on the application that I’m confident will help in the scenarios described. Potential features (subject to change):
1. A way to use features reliant on the tap&hold mechanic, but without tap and holding. This would consist of a button (for visual feedback) linked to the keyboard Shift key such that whenever active (button enabled or shift pressed), interactions will use those features without delay (or minimal delay). Example: adding a layer without waiting. I’m confident this will help speed up quite a few repetitive tasks.
2. Holding Alt key and tapping in the front view mode will clone the currently selected layer (symbol/container) at the position tapped. Example: adding layers without leaving front view mode. I’m confident this will allow more focus on drawing itself.
3. Folder-style list of containers and symbols (a barebone version of this exists in the bottom right corner of side view mode) in front AND side view modes, containing options for expanding/collapsing containers, quick selecting layers, searching layer names, renaming, and deleting. This one is similar to the legacy side menu, but redesigned. I’m confident this will let users navigate through the stack of layers much more quickly.

I’ll update this issue when I have anything more of significance to say. Let me know your thoughts on this.

**Comment by malulleybovo** [comment]
Please check out the newest release, which includes improvements based on user feedback.

https://github.com/malulleybovo/SymbolArtEditorOnline/releases/tag/v2.1.0

Feel free to reopen the issue or create a new one for further discussion.

**Comment by Axellogic** [comment]
I mean the side view of the groups helps a little but its also much too small on the screen space so I can only see a tiny amount of the list. This still results in too much scrolling. 
Every extra key or action you add in order to perform an action just makes en entire thing less efficient. Getting rid of hold is good but then you added another input in that I have to hold shift now.  Like if it was hold shift quickly adds a new layer while in 2d mode, that would be increased efficiency. Instead its just another barrier after I already toggle to 3d mode then I toggle add symbol and only after that do I hold shift and click (also you still have to hold it for a few milliseconds just tapping doesn't work, though it does create the symbol much faster). I get that you likely do it so that layers don't accidentally get added when click and dragging to scroll the 3d list, but that just speaks to how inefficient the 3d view is itself. As stated before I still don't get what benefit the 3d has beyond adding more inputs before being able to add a symbol. 
The Old version's UI was very clear and simple. If it was taking up too much space, hiding it was simple. If I need to train myself to use a UI, its not efficient. I am still much more inclined to just use the old version than even attempt to use the current. Its a shame cause I can tell it loads faster and is cleaner but its not worth the extra trouble.

**Comment by malulleybovo** [comment]
Hello,

I appreciate the feedback. I understand you're frustrated, so you're only focusing on the negatives to see what can be done about it. So lets go one step at a time.

> I mean the side view of the groups helps a little but its also much too small on the screen space so I can only see a tiny amount of the list. This still results in too much scrolling.

I've considered this. I have yet to find a way to give enough scrolling space without cluttering the view with UI. I've thought about a maximize/minimize button on the list to only leave it expanded when you actually need it, but that's subject to change and I can't promise when this may get added.

> Like if it was hold shift quickly adds a new layer while in 2d mode, that would be increased efficiency. Instead its just another barrier after I already toggle to 3d mode then I toggle add symbol and only after that do I hold shift and click

Have you tried holding `Control` and clicking while in the front view mode (2d)? That creates a clone of what's currently selected where you clicked. Check out the release notes https://github.com/malulleybovo/SymbolArtEditorOnline/releases/tag/v2.1.0

> (also you still have to hold it for a few milliseconds just tapping doesn't work, though it does create the symbol much faster)

It's set up with a debouncing time of 25 milliseconds to avoid misinterpretation of the tap action. 25 milliseconds is really fast. Unless you either tap extremely fast or your browser suffers FPS issues rendering the canvas, you won't have issues with this. So out of curiosity, how fast are the transitions in your browser when running the application? Do you see a delay when moving things around of when changing view modes (2d/3d)? If so, this is indicative of FPS issues and I would recommend a few options like making sure that hardware acceleration is enabled in the browser, or setting the browser to use your dedicated GPU instead of integrated graphics card (built into the CPU and used by default). What's the OS and browser used? (ex: Win10-Chrome).

You may experience lag in the application if you're running intensive tasks on the GPU while using this application (like running a game and using this at the same time). This depends on how powerful and optimized the hardware is.

> As stated before I still don't get what benefit the 3d has beyond adding more inputs before being able to add a symbol.

The 3D aspect of the editor is to make the symbol art more visual in the sense that you are stacking layers upon layers in a certain order to make symbols look like an actual image. A list of text with symbol thumbnails like the one in game and the one in the legacy version simply doesn't convey that effectively so the barrier for entry in this art space is unnecessarily high. While this is designed to be beginner-friendly, I understand this may not appeal to people who have put up with that old layout and got used to it. So to give these individuals the speed they need, there are shortcuts and extra features (like the new layer list in front view mode) that aim to reduce effort from repetitive tasks. But they need to be learned like any other windows shortcut for instance (it becomes muscle memory fairly quickly).
