### ISSUE TITLE
Colors not applying to symbols.

### ISSUE THREAD

**Issue by goremageddon** [malulleybovo/SymbolArtEditorOnline#2]
Can't change colors on symbols in browser version.

**Comment by scege** [comment]
If you're using chrome, turn on hardware acceleration, that fixed it for me.

**Comment by malulleybovo** [comment]
Indeed there is an unspoken requirement for hardware acceleration while running the editor  (which modern browsers set as default) since it deals with graphic computation, and that benefits from hardware acceleration. Please make sure you have hardware acceleration enabled (in Settings of your browser of preference) while running the editor to avoid unexpected behavior such as what you reported. Note that upon changing this setting in the browser, they normally require you to restart the browser.

**Comment by goremageddon** [comment]
Ah. Thanks, I usually disable HA because of incompatibility with windows HDR and screenshots but ill give it a shot.
