### ISSUE TITLE
Exporting as a PNG

### ISSUE THREAD

**Issue by WeForgot** [malulleybovo/SymbolArtEditorOnline#22]
Hi there,

I was curious if there were any plans to ever add back the ability to export a Symbol Art as a PNG. I tried creating a Python script that did this exact thing (using your JS as a template) but it was a bit harder than I expected. If not that is fine, it was a feature on the older version so I was curious. Thanks!

WeForgot

**Comment by malulleybovo** [comment]
Hello,

The feature to download as png wasn’t included in v2.0.0 simply because its priority is low, since pngs cannot be imported in game nor in this editor.

On that note, I had a bit of time and this one is relatively simple to make so I put it together and released it in v2.3.0. You can check it out now at the options menu as “S.A. SCREENSHOT”.

**Comment by WeForgot** [comment]
You are a saint. Thank you so much!
