### ISSUE TITLE
"i" key function becomes unusable if typed while renaming layer

### ISSUE THREAD

**Issue by shotgunbuddy** [malulleybovo/SymbolArtEditorOnline#3]
"i" currently functions to temporarily change the transparency of the background/reference image. If you rename a layer that has "i" in the name, the background is set as if the "i" key is being held down constantly.

The background can still be changed by editing it normally to set the transparency but the "i" key functionality is lost until the page is reloaded.

**Comment by malulleybovo** [comment]
Thank you for reporting this bug. There does seem to be a bug with this feature. It seems like whenever "i" is used when renaming, the background image "disappears." As a work around until this bug is fixed, whenever this happens, you can: (given that you have uploaded a helper image already)
1) Go to the image button in the menu, then to the pencil button that pops up.
![image](https://user-images.githubusercontent.com/14852459/83599691-32174880-a543-11ea-9a1d-ff1d2704f125.png)
2) Then in the top right panel, change the value of "transparency" by dragging it around.
![image](https://user-images.githubusercontent.com/14852459/83599803-7d315b80-a543-11ea-9893-58ab5d3ce82a.png)

This should reset the state of the helper image.

**Comment by malulleybovo** [comment]
The issue has been resolved in the latest release.
