### ISSUE TITLE
Overlay Image

### ISSUE THREAD

**Issue by Xiiovii** [malulleybovo/SymbolArtEditorOnline#8]
Hello! 

I'm having issues with the overlay image. When I open the overlay image to use as a reference, it is ridiculously dark and hard to see. I'm not sure why it's so dark, because the image in the gif for the tutorial looks normal when transparent. This goes for all images I post, and I'm not sure if that's what it's supposed to do or not because it makes referencing it very hard...

Here's some examples with some of my art that I'm trying to use:
![](https://puu.sh/FWyIe/3e75103cf9.png) What it looks like when I upload it.
![RAEG](https://user-images.githubusercontent.com/66939558/84629227-d2079700-ae9e-11ea-9d38-db79b2f0e38e.png) What it's supposed to look like. 

![](https://puu.sh/FWyKx/cc017cfac4.png) Another example of what it looks like when I upload it.
![](https://puu.sh/FWyLc/fee8d2fd1b.png) Vs what it's supposed to look like.

I just wasn't sure if this is what it's supposed to be like or not. :( If it is then that's fine, I can  just lighten it up in my art program and try it that way, but just in case this isn't intentional I thought I'd say something.

What's weird is that before it did this, I had hardware acceleration turned off and it was totally fine. Obviously I couldn't change the color of symbols or do transparency but when I turned on hardware acceleration, the overlay image turned super dark like that. 

Here's what it looks like with hardware acceleration turned off, albeit a bit more funky looking with those lines and stuff. 
![](https://puu.sh/FWyPq/976ff66f2c.png)

When I turn it back on, it goes back to being dark. 

Thanks so much for reading!

Edit: Looking at it again, it looks like not only is the image I upload darker than usual, but the colors itself appear darker than they actually are. So this seems to be not only an image with the overlay but with the colors appearing darker in general. Again, not sure if it's something on my end or with the editor itself...

Example: 

![](https://puu.sh/FWzPU/6795f75e39.png)
The color in the picker is lighter than what actually appears in the editor itself. 

![](https://puu.sh/FWzSu/faad8aa076.png)
Another example, with the color in the picker, again, being lighter than the color on the editor.

**Comment by malulleybovo** [comment]
Thanks for your in depth explanation. You have touched a very interesting topic. As it turns out, the game itself applies a custom filter to the game frames, which modifies the original colors of the SA. This filter generally darkens the symbols a bit in game. Since the editor in game contains a color picker that also has the same filter applied to it, you normally don't notice it, but if you look at the .sar data, the color for each symbol is not the exact same color that shows on your screen in game.
To provide a more accurate color representation of SAs in this editor, I have included a custom filter that mimics the one used in the game. This makes the colors shown in the editor much more accurate when compared to the ones shown in game. However, as a drawback, it makes the color not as accurate when compared to the true colors behind the symbols.
This drawback is what you have observed. The images you import as well as the color picker both use the real colors, but the editor uses the filtered colors. Thus the inaccuracy in the color.
This is indeed a bug, or two. The imported images should not be filtered so as to display the real colors. And the color picker should be filtered so that the color you pick is the exact color that shows.
I'll look into how this can be done.

**Comment by malulleybovo** [comment]
The issue has been resolved in the latest release.
